/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as MiningRouteImport } from './routes/mining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssociationRouteImport } from './routes/association'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoute = MiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationRoute = AssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/mining': typeof MiningRoute
  '/real-estate': typeof RealEstateRoute
  '/services': typeof ServicesRoute
  '/trade': typeof TradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/mining': typeof MiningRoute
  '/real-estate': typeof RealEstateRoute
  '/services': typeof ServicesRoute
  '/trade': typeof TradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/mining': typeof MiningRoute
  '/real-estate': typeof RealEstateRoute
  '/services': typeof ServicesRoute
  '/trade': typeof TradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/association'
    | '/contact'
    | '/mining'
    | '/real-estate'
    | '/services'
    | '/trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/association'
    | '/contact'
    | '/mining'
    | '/real-estate'
    | '/services'
    | '/trade'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/association'
    | '/contact'
    | '/mining'
    | '/real-estate'
    | '/services'
    | '/trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssociationRoute: typeof AssociationRoute
  ContactRoute: typeof ContactRoute
  MiningRoute: typeof MiningRoute
  RealEstateRoute: typeof RealEstateRoute
  ServicesRoute: typeof ServicesRoute
  TradeRoute: typeof TradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association': {
      id: '/association'
      path: '/association'
      fullPath: '/association'
      preLoaderRoute: typeof AssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssociationRoute: AssociationRoute,
  ContactRoute: ContactRoute,
  MiningRoute: MiningRoute,
  RealEstateRoute: RealEstateRoute,
  ServicesRoute: ServicesRoute,
  TradeRoute: TradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
